### ISSUE TITLE
Status of the project -- release strategy?

### ISSUE THREAD

**Issue by fzimmermann89** [flatironinstitute/pytorch-finufft#106]
Hi,

the last commit was quite some time ago, and the code seems to be in a good condition with only few minor open enhancement issues.

Maybe it would now be a good time to consider either putting it on pypi and getting it into conda-forge ? 
This would make it easier for other packages to depend on it.

Thank you for your work,
Felix

**Comment by eickenberg** [comment]
Thanks! Yes, that would indeed be a good idea.

Unclear if we have anybody with available cycles to do this right now
unfortunately.

**Comment by WardBrian** [comment]
I can next week. Will need to make sure recent finufft changes didn’t break anything first

**Comment by WardBrian** [comment]
I just uploaded the current state of the repo to PyPI: https://pypi.org/project/pytorch-finufft/



@eickenberg if https://pypi.org/user/meickeick/ is you I can also add you to the pypi owners list. I also added a basic github action here to do releases, which has the proper permissions set up
