### ISSUE TITLE
Q: Why should the points lie in -3pi .. 3pi?

### ISSUE THREAD

**Issue by fzimmermann89** [flatironinstitute/pytorch-finufft#108]
I am a bit confused by the docstring of the functional transforms.

Why should the non-uniform points lie in -3pi..3pi ?
I assume tthey are folded to 0..2pi?
If that's the case, it could be the more useful information.

If not, why is the function periodic with 6pi period?

Thanks :)

**Comment by WardBrian** [comment]
This is something we inherit from finufft, explained here: https://finufft.readthedocs.io/en/latest/math.html

essentially, your data should still be in a 2-pi periodic domain, but you can pick where it starts (eg, the wider restriction allows you to pick 0,2pi, or -pi,pi, or more)

**Comment by fzimmermann89** [comment]
Thanks for the explanation and great that the  restriction got removed!

Maybe now consider changing the docstring to something simpler to understand?
Naively, the current docstring would suggest to me to match the torch.fft result, one should scale the points to lie in -3pi..3pi.
A small hint here that the points are supposed to be in a 2pi interval would maybe make it more beginner friendly?

**Comment by WardBrian** [comment]
Yes, worth documenting. Thanks for the heads up @janden
