### ISSUE TITLE
ENH ifft functions or ifft mode in our current functions?

### ISSUE THREAD

**Issue by eickenberg** [flatironinstitute/pytorch-finufft#87]
In making an example, I found myself requiring an ifft equivalent. This can be achieved with our current functions by flipping the isign and adding a normalization of the output. This is a bit obscure to obtain and maybe we need a shortcut for it

**Comment by WardBrian** [comment]
I think it would be fine to write these as small extra functions (which I prefer to adding more arguments to the existing) that call the primary implementations
