### ISSUE TITLE
ENH reason for using `setup_context`: vmappability

### ISSUE THREAD

**Issue by eickenberg** [flatironinstitute/pytorch-finufft#95]
@Matematija found this error while trying to vmap one of our functions:

```python
RuntimeError: In order to use an autograd.Function with functorch transforms (vmap, grad, jvp, jacrev, ...), it must override the setup_context staticmethod. For more details, please see https://pytorch.org/docs/master/notes/extending.func.html
```

**Comment by WardBrian** [comment]
Is vmapping preferrable to us supporting multiple values at once (#63)?

Updating our methods to use setup_context should be pretty trivial, my question is just if that is really the best thing to be trying

**Comment by Matematija** [comment]
The page linked in the error message (https://pytorch.org/docs/master/notes/extending.func.html#torch-vmap-support) has a good tutorial of what needs to be done to get `torch.vmap` and friends to work. I'm happy to do a quick PR if that is cool with you guys.

After a quick read, it seems to me that all that needs to happen is basically this:
```python
class Foo(torch.autograd.Function):
    # (...)
    @staticmethod
    def vmap(info, in_dims: Tuple[Optional[int]], *args):
        # (....)
```

**Comment by WardBrian** [comment]
That seems better than letting PyTorch figure out its own vmap, since the values should be batched through finufft rather than just looping (which I think we would need to do for the points)

**Comment by Matematija** [comment]
Agreed. Do you think that the point vmap should happen on the C++ side of the code? In other words, would it be too much to compile one additional function that does the asynchronous for-loop? Or is a python-side for-loop good enough?

**Comment by WardBrian** [comment]
For points? I’d say a python for loop is good enough until we have a reason to think otherwise

**Comment by Matematija** [comment]
Ok, cool. Would you like me to do a quick PR?

**Comment by WardBrian** [comment]
If you’d like to, sure! Otherwise I can take a pass myself first thing next week

**Comment by Matematija** [comment]
Oh, ok. 😅 In that case, I better leave it to you because "quick" means next week for me.

**Comment by WardBrian** [comment]
I've started a branch here: https://github.com/flatironinstitute/pytorch-finufft/tree/enh/vmap

The points derivative is already implemented with batching over values in the backwards pass, so I need to figure out the indexing required to do both of those batches at once. It should not be that hard, but it's doing my head in for the moment

**Comment by WardBrian** [comment]
@Matematija - were you just trying a normal `vmap`?

It seems like we can easily support this, but some of the more complicated functions like `jacrev` may require us to rethink our backward pass, based on this paragraph from the torch docs:

> In order for the [torch.autograd.Function](https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function) to be arbitrarily composable with function transforms, we recommend that all other staticmethods other than [forward()](https://pytorch.org/docs/stable/generated/torch.autograd.Function.forward.html#torch.autograd.Function.forward) and setup_context() must be transformable: that is, they must consist of only PyTorch operators or call other [torch.autograd.Function](https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function) (that may call into C++/CUDA/etc).

Currently our backward pass also calls into C++/CUDA, but it may be possible to re-write it such that it only uses the functionals.

**Comment by Matematija** [comment]
For now, I'm looking for just a normal `torch.vmap` but later down the road, other AD tools would be nice as well.

(P.S. I am also experimenting with the recent [JAX GPU PR](https://github.com/dfm/jax-finufft/tree/2023-gpu) which does `vmap` out of the box.)
