### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Matematija** [flatironinstitute/pytorch-finufft#99]
Hi - I ran into a problem that looks like a memory leak. I define my model using a custom Fourier convolution layer that uses `pytorch-finufft`. In the optimization loop, after approximately epoch ~50 I get a standard CUDA OOM error:

```
OutOfMemoryError: CUDA out of memory. Tried to allocate 1.48 GiB. GPU 0 has a total capacty of 23.61 GiB of which 527.88 MiB is free. Including non-PyTorch memory, this process has 22.54 GiB memory in use. Of the allocated memory 15.10 GiB is allocated by PyTorch, and 3.19 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

The error disappears when I exclude the Fourier convolution layer (and with it any calls to `pytorch-finufft`). This one is a bit tricky to give a minimal example for and I am not sure if it has anything to do with `pytorch-finufft`.

FWIW, this is the conv function in question:
```python
from pytorch_finufft.functional import finufft_type1 as nufft1, finufft_type2 as nufft2

def _scale_grid(x):

    xmin, _ = x.min(dim=-1, keepdim=True)
    xmax, _ = x.max(dim=-1, keepdim=True)

    x0 = (xmin + xmax) / 2
    L = xmax - xmin

    xs = 2 * torch.pi * (x - x0) / L
    volume = torch.prod(L, dim=-2)

    return xs, volume

def to_complex(t: Tensor) -> Tensor:
    
    if t.is_complex():
        return t
    elif t.dtype == torch.float32:
        return t.to(torch.complex64)
    elif t.dtype == torch.float64:
        return t.to(torch.complex128)
    else:
        raise TypeError(f"Cannot convert tensor of type {t.dtype} to complex.")

@partial(torch.vmap, in_dims=(0, 0, None))
def cconv(f: Tensor, x: Tensor, kernel: Tensor, *, eps: float = 1e-6) -> Tensor:

    # f.shape = (..., n_channels, npts)
    # x.shape = (..., ndim, npts)
    # kernel.shape = (..., in_channels, out_channels, *grid_shape)

    xs, volume = _scale_grid(x)

    f_hat = nufft1(xs, to_complex(f), kernel.shape[2:], isign=1, eps=eps)
    c_hat = torch.einsum("i...,io...->o...", f_hat, to_complex(kernel) / volume)
    c = nufft2(xs, c_hat, isign=-1, eps=eps)

    return torch.real(c)
```

**Comment by WardBrian** [comment]
Can you try some of the methods described on [this page](https://pytorch.org/docs/stable/torch_cuda_memory.html#torch-cuda-memory) to visualize memory usage? I don't think it is necessary to run until the OOM error, just until we can see a trend in the graph to try to track down

**Comment by Matematija** [comment]
The plot thickens.

I did both approaches simultaneously (track memory + printouts) but this time around the entire python kernel crashes. My jupyter notebook just throws:

```
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter log for further details.
```

I did also do a shorter run (~20 epochs) and saved the memory history pickle file. It is not showing any systematic memory increase over time. Happy to share it if you want to take a look.

I'm very confused now.

**Comment by WardBrian** [comment]
@Matematija - do you still have this code/happen to remember if you were using cuda 11.8?

**Comment by Matematija** [comment]
Sorry - I didn't see this when this was posted. I can confirm was using CUDA 11.8.

**Comment by WardBrian** [comment]
Ok, we believe a known memory leak in CuFFT was likely the underlying cause then
